name: registrytest

on:
 
  workflow_dispatch:

jobs:

  test-setup-v4:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Node.js for GitHub Packages Registry
      - uses: ThisIsManta/setup-node@volta-extends

   
  version-file-volta:
              runs-on: ${{ matrix.os }}
              strategy:
                fail-fast: false
                matrix:
                  os: [ubuntu-latest, windows-latest, macos-latest]
              steps:
                - uses: actions/checkout@v4
                - name: Setup node from node version file
                  uses: ./
                  with:
                    node-version-file: '__tests__/data/package-volta.json'
                - name: Verify node
                  run: __tests__/verify-node.sh 16

  version-file-volta-extends:
              runs-on: ${{ matrix.os }}
              strategy:
                fail-fast: false
                matrix:
                  os: [ubuntu-latest, windows-latest, macos-latest]
              steps:
                - uses: actions/checkout@v4
                - name: Setup node from node version file
                  uses: ./
                  with:
                    node-version-file: '__tests__/data/package-volta-extends.json'
                - name: Verify node
                  run: __tests__/verify-node.sh 16

    

         
