name: registrytest

on:
 
  workflow_dispatch:

jobs:
   
  version-file-volta:
              runs-on: ${{ matrix.os }}
              strategy:
                fail-fast: false
                matrix:
                  os: [ubuntu-latest, windows-latest, macos-latest]
              steps:
                - name: Setup node from node version file
                  uses: ThisIsManta/setup-node@volta-extends
                - uses: actions/checkout@v4
                  with:
                    node-version-file: '__tests__/data/package-volta.json'
               
            

  version-file-volta-extends:
              runs-on: ${{ matrix.os }}
              strategy:
                fail-fast: false
                matrix:
                  os: [ubuntu-latest, windows-latest, macos-latest]
              steps:
                - name: Setup node from node version file
                  uses: ThisIsManta/setup-node@volta-extends
                - uses: actions/checkout@v4
                  with:
                    node-version-file: '__tests__/data/package-volta-extends.json'
               

    

         
