name: registrytest

on:
 
  workflow_dispatch:

jobs : 
 
 version-file-volta:
              runs-on: ${{ matrix.os }}
              strategy:
                fail-fast: false
                matrix:
                  os: [ubuntu-latest, windows-latest, macos-latest]
              steps:
                - uses: actions/checkout@v4
                  
                - name: Setup node from node version file
                  uses: ThisIsManta/setup-node@volta-extends
                  with:
                    node-version-file: 'package-volta.json'
                - name: Verify node
                  run: _tests_/verify-node.sh 18

            

 version-file-volta-extends:
              runs-on: ${{ matrix.os }}
              strategy:
                fail-fast: false
                matrix:
                  os: [ubuntu-latest, windows-latest, macos-latest]
              steps:
                - uses: actions/checkout@v4
                  
                - name: Setup node from node version file
                  uses: ThisIsManta/setup-node@volta-extends
                  with:
                    node-version-file: 'package-vota-extends.json'
                - name: Verify node
                  run: _tests_/verify-node.sh 18
