name: registrytest

on:
 
  workflow_dispatch:

jobs:

  test-setup-v4:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Setup dotnet 2.2.402, 3.1.404 and 3.0.x
      - uses: actions/setup-node@v4
      

      - name: Node.js for GitHub Packages Registry
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Packages Registry
        # This will not build the package again, if we already generated the
        # prebuild for the operating system and CPU where this job is running.
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Node.js for npmjs
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npmjs
        # This will not build the package again, if we already generated the
        # prebuild for the operating system and CPU where this job is running.
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
